export const GET_PAYMENT_PLANS_START = "GET_PAYMENT_PLANS_START";
export const GET_PAYMENT_PLANS_SUCCESS = "GET_PAYMENT_PLANS_SUCCESS";
export const GET_PAYMENT_PLANS_FAIL = "GET_PAYMENT_PLANS_FAIL";
export const MAKE_PAYMENT_START = "MAKE_PAYMENT_START";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_FAIL = "MAKE_PAYMENT_FAIL";